package uk.ac.ed.inf.mpatsis.sstubs.core;
/**
 * @author mpatsis
 *
 */
public enum BugType{
	DIFFERENT_METHOD_SAME_ARGS, 
	SWAP_ARGUMENTS,
	SWAP_BOOLEAN_LITERAL,
	OVERLOAD_METHOD_DELETED_ARGS, 
	OVERLOAD_METHOD_MORE_ARGS, 
	CHANGE_OPERATOR,
	CHANGE_UNARY_OPERATOR,
	CHANGE_OPERAND,
	CHANGE_MODIFIER,
	CHANGE_IDENTIFIER,
	CHANGE_NUMERAL,
	CHANGE_CALLER_IN_FUNCTION_CALL,
	ADD_THROWS_EXCEPTION,
	DELETE_THROWS_EXCEPTION,
	MORE_SPECIFIC_IF,
	LESS_SPECIFIC_IF
}